// <auto-generated />
using System;
using MedApp.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230522170644_Finale")]
    partial class Finale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedApp.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Allergy", b =>
                {
                    b.Property<int>("MedCardId")
                        .HasColumnType("integer");

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer");

                    b.HasKey("MedCardId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("MedApp.Models.Entities.AnamnesisVitae", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Heredity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HospitalizationID")
                        .HasColumnType("integer");

                    b.Property<string>("LifeAnamnesis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PastDiseases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HospitalizationID");

                    b.ToTable("AnamnesisVitae");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Cabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Cabinets");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Chamber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BedCount")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Chambers");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Checkups", b =>
                {
                    b.Property<int>("HospitalizationId")
                        .HasColumnType("integer");

                    b.Property<int>("CheckUpId")
                        .HasColumnType("integer");

                    b.Property<int>("Checkup_sCheckUpId")
                        .HasColumnType("integer");

                    b.Property<int>("Checkup_sHospitalizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospitaliztionId")
                        .HasColumnType("integer");

                    b.Property<int?>("СheckupId")
                        .HasColumnType("integer");

                    b.HasKey("HospitalizationId", "CheckUpId");

                    b.HasIndex("СheckupId");

                    b.HasIndex("Checkup_sHospitalizationId", "Checkup_sCheckUpId");

                    b.ToTable("Checkups");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Diagnoses", b =>
                {
                    b.Property<int>("HospitalizationId")
                        .HasColumnType("integer");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("HospitalizationId", "DiagnosisId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClinaclDiagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EtiologyPathogenesis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MkbId")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyndromicDiagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MkbId");

                    b.ToTable("Diagnosis_s");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospitalizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("HospitalizationId");

                    b.HasIndex("UserId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Hospitalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnamnesisMorbi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HospitalizationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospitalizationMethod")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAcrive")
                        .HasColumnType("boolean");

                    b.Property<int>("MedCardId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDiagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Сomplaints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedCardId");

                    b.ToTable("Hospitalizations");
                });

            modelBuilder.Entity("MedApp.Models.Entities.MedCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MainPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OmsNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportSeries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressID");

                    b.ToTable("MedCards");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Mkb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mkbs");
                });

            modelBuilder.Entity("MedApp.Models.Entities.PatientInChamber", b =>
                {
                    b.Property<int>("MedCardId")
                        .HasColumnType("integer");

                    b.Property<int>("ChamberId")
                        .HasColumnType("integer");

                    b.HasKey("MedCardId", "ChamberId");

                    b.HasIndex("ChamberId");

                    b.ToTable("PatientInChambers");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospitalizationId")
                        .HasColumnType("integer");

                    b.Property<int>("NewChamberId")
                        .HasColumnType("integer");

                    b.Property<int>("OldChamberId")
                        .HasColumnType("integer");

                    b.Property<string>("Spor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HospitalizationId");

                    b.HasIndex("NewChamberId");

                    b.HasIndex("OldChamberId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HospitalizationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStopped")
                        .HasColumnType("boolean");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("HospitalizationId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("MedApp.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Сheckup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genitourinary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Heart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hormones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nervous")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stomach")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Checkup_s");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Allergy", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Allergen", "Allergen")
                        .WithMany("Allergies")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.MedCard", "MedCard")
                        .WithMany("Allergies")
                        .HasForeignKey("MedCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("MedCard");
                });

            modelBuilder.Entity("MedApp.Models.Entities.AnamnesisVitae", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Hospitalization", "Hospitalization")
                        .WithMany("AnamnesisVitae")
                        .HasForeignKey("HospitalizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospitalization");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Cabinet", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Department", "Department")
                        .WithMany("Cabinets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Chamber", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Department", "Department")
                        .WithMany("Chambers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.User", "User")
                        .WithMany("Chambers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Checkups", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Hospitalization", "Hospitalization")
                        .WithMany("Checkups")
                        .HasForeignKey("HospitalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.Сheckup", null)
                        .WithMany("Checkups")
                        .HasForeignKey("СheckupId");

                    b.HasOne("MedApp.Models.Entities.Checkups", "Checkup_s")
                        .WithMany()
                        .HasForeignKey("Checkup_sHospitalizationId", "Checkup_sCheckUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkup_s");

                    b.Navigation("Hospitalization");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Diagnoses", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Diagnosis", "Diagnosis")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.Hospitalization", "Hospitalization")
                        .WithMany("Diagnoses")
                        .HasForeignKey("HospitalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("Hospitalization");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Diagnosis", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Mkb", "Mkb")
                        .WithMany("DiagnosisCollection")
                        .HasForeignKey("MkbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mkb");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Examination", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Cabinet", "Cabinet")
                        .WithMany("Examinations")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.Hospitalization", "Hospitalization")
                        .WithMany("Examinations")
                        .HasForeignKey("HospitalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.User", "User")
                        .WithMany("Examinations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Hospitalization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Hospitalization", b =>
                {
                    b.HasOne("MedApp.Models.Entities.MedCard", "MedCard")
                        .WithMany("Hospitalizations")
                        .HasForeignKey("MedCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedCard");
                });

            modelBuilder.Entity("MedApp.Models.Entities.MedCard", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Address", "Address")
                        .WithMany("Cards")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MedApp.Models.Entities.PatientInChamber", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Chamber", "Chamber")
                        .WithMany("PatientsInChamber")
                        .HasForeignKey("ChamberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.MedCard", "MedCard")
                        .WithMany("PatientInChambers")
                        .HasForeignKey("MedCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamber");

                    b.Navigation("MedCard");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Transaction", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Hospitalization", "Hospitalization")
                        .WithMany("Transactions")
                        .HasForeignKey("HospitalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.Chamber", "NewChamber")
                        .WithMany("NewChamber")
                        .HasForeignKey("NewChamberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.Chamber", "OldChamber")
                        .WithMany("OldChamber")
                        .HasForeignKey("OldChamberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospitalization");

                    b.Navigation("NewChamber");

                    b.Navigation("OldChamber");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Treatment", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Hospitalization", "Hospitalization")
                        .WithMany("Treatments")
                        .HasForeignKey("HospitalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospitalization");
                });

            modelBuilder.Entity("MedApp.Models.Entities.User", b =>
                {
                    b.HasOne("MedApp.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedApp.Models.Entities.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Address", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Allergen", b =>
                {
                    b.Navigation("Allergies");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Cabinet", b =>
                {
                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Chamber", b =>
                {
                    b.Navigation("NewChamber");

                    b.Navigation("OldChamber");

                    b.Navigation("PatientsInChamber");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Department", b =>
                {
                    b.Navigation("Cabinets");

                    b.Navigation("Chambers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Diagnosis", b =>
                {
                    b.Navigation("Diagnoses");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Hospitalization", b =>
                {
                    b.Navigation("AnamnesisVitae");

                    b.Navigation("Checkups");

                    b.Navigation("Diagnoses");

                    b.Navigation("Examinations");

                    b.Navigation("Transactions");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("MedApp.Models.Entities.MedCard", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Hospitalizations");

                    b.Navigation("PatientInChambers");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Mkb", b =>
                {
                    b.Navigation("DiagnosisCollection");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MedApp.Models.Entities.User", b =>
                {
                    b.Navigation("Chambers");

                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("MedApp.Models.Entities.Сheckup", b =>
                {
                    b.Navigation("Checkups");
                });
#pragma warning restore 612, 618
        }
    }
}
